name: Build & Release APK
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.kt"
      - "**/*.xml"
      - "**/*.gradle.kts"
      - "gradle/libs.versions.toml"
      - "gradle/wrapper/**"
      - "gradle.properties"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    uses: mapgie/android-Actions/.github/workflows/android-build-release.yml@14f72d0acca36d4ce4dcc643beac4c42ca6fe3ab
    with:
      app-name: GoFlo
