name: Build & Release APK
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.kt"
      - "**/*.xml"
      - "**/*.gradle.kts"
      - "gradle/libs.versions.toml"
      - "gradle/wrapper/**"
      - "gradle.properties"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    uses: mapgie/android-Actions/.github/workflows/android-build-release.yml@d99437fe573b99a7730fd9dcc05c58535143eaf0
    with:
      app-name: GoFlo
      create-release: ${{ github.event_name == 'workflow_dispatch' }}
