name: Changelog bump check
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.kt"
      - "**/*.xml"
      - "**/*.gradle.kts"
      - "gradle/libs.versions.toml"
permissions:
  contents: read
jobs:
  check:
    uses: mapgie/android-Actions/.github/workflows/changelog-check.yml@dd75ec70a809295343d167556395fc3cfddb0242
